{
  return Utils.exceptionCauseIsInstanceOf(exceptionCause,(Throwable)throwable);
}
